export { parseFrontmatter, type FrontmatterResult } from "./frontmatter"
export { executeHookCommand, executeCommand, resolveCommandsInText, type CommandResult, type ExecuteHookOptions } from "./command-executor"
export { containsPath, isWithinProject } from "./contains-path"
export { resolveFileReferencesInText } from "./file-reference-resolver"
export { sanitizeModelField } from "./model-sanitizer"
export { log, logDebug, logWarn, logError, getLogFilePath, setLogLevel, getLogLevel, setLogLevelFromEnv } from "./logger"
export { camelToSnake, snakeToCamel, transformObjectKeys, objectToSnakeCase, objectToCamelCase } from "./snake-case"
export { transformToolName } from "./tool-name"
export { matchesToolMatcher, findMatchingHooks } from "./pattern-matcher"
export { isHookDisabled } from "./hook-disabled"
export { isPlainObject, deepMerge } from "./deep-merge"
export { isMarkdownFile, isSymbolicLink, resolveSymlink, resolveSymlinkAsync } from "./file-utils"
export { truncateToTokenLimit, getContextWindowUsage, dynamicTruncate, createDynamicTruncator, type TruncationResult, type TruncationOptions } from "./dynamic-truncator"
export { getDataDir, getOpenCodeStorageDir, getCacheDir, getHiaiOpenCodeCacheDir, getOpenCodeCacheDir } from "./data-path"
export { captureLearn, getRelevantLearns, getRecentLearns, formatLearnEntriesForPrompt, type LearnEntry } from "./learn-system"
export { getConfigLoadErrors, clearConfigLoadErrors, addConfigLoadError, type ConfigLoadError } from "./config-errors"
export { getClaudeConfigDir } from "./claude-config-dir"
export { getAgentsConfigDir } from "./agents-config-dir"
export { parseJsonc, parseJsoncSafe, readJsoncFile, detectConfigFile, detectPluginConfigFile, type JsoncParseResult } from "./jsonc-parser"
export { AGENT_NAME_MAP, BUILTIN_AGENT_NAMES, migrateAgentNames, HOOK_NAME_MAP, migrateHookNames, MODEL_VERSION_MAP, migrateModelVersions, MODEL_TO_CATEGORY_MAP, migrateAgentConfigToCategory, shouldDeleteAgentConfig, migrateConfigFile } from "./migration"
export { TAURI_APP_IDENTIFIER, TAURI_APP_IDENTIFIER_DEV, isDevBuild, getOpenCodeConfigDir, getOpenCodeConfigPaths, detectExistingConfigDir } from "./opencode-config-dir"
export { resolveAgentDefinitionPaths } from "./resolve-agent-definition-paths"
export type {
  OpenCodeBinaryType,
  OpenCodeConfigDirOptions,
  OpenCodeConfigPaths,
} from "./opencode-config-dir-types"
export { MINIMUM_OPENCODE_VERSION, OPENCODE_NATIVE_AGENTS_INJECTION_VERSION, OPENCODE_SQLITE_VERSION, parseVersion, compareVersions, getOpenCodeVersion, isOpenCodeVersionAtLeast, resetVersionCache, setVersionCache } from "./opencode-version"
export { isSqliteBackend, resetSqliteBackendCache } from "./opencode-storage-detection"
export { createAgentToolRestrictions, createAgentToolAllowlist, migrateToolsToPermission, migrateAgentConfig, type PermissionValue, type PermissionFormat } from "./permission-compat"
export { detectExternalNotificationPlugin, detectExternalSkillPlugin, getNotificationConflictWarning, getSkillPluginConflictWarning, type ExternalNotifierResult, type ExternalSkillPluginResult } from "./external-plugin-detector"
export { extractZip } from "./zip-extractor"
export { getCachedBinaryPath, ensureCacheDir, downloadArchive, extractTarGz, extractZipArchive, cleanupArchive, ensureExecutable } from "./binary-downloader"
export { writeFileAtomically } from "./write-file-atomically"
export { resolveAgentVariant, resolveVariantForModel, applyAgentVariant } from "./agent-variant"
export { consumeNewMessages, resetMessageCursor, getMessageCursor, restoreMessageCursor, type CursorMessage, type CursorState } from "./session-cursor"
export { detectShellType, shellEscape, buildEnvPrefix, shellEscapeForDoubleQuotedCommand, type ShellType } from "./shell-env"
export { SYSTEM_DIRECTIVE_PREFIX, createSystemDirective, isSystemDirective, hasSystemReminder, removeSystemReminders, SystemDirectiveTypes, type SystemDirectiveType } from "./system-directive"
export { getAgentToolRestrictions, hasAgentToolRestrictions } from "./agent-tool-restrictions"
export { AGENT_MODEL_REQUIREMENTS, CATEGORY_MODEL_REQUIREMENTS, initializeModelRequirements, type FallbackEntry, type ModelRequirement } from "./model-requirements"
export { resolveModel, resolveModelWithFallback, normalizeFallbackModels, flattenToFallbackModelStrings, type ModelResolutionInput, type ModelSource, type ExtendedModelResolutionInput } from "./model-resolver"
export { normalizeModel, normalizeModelID } from "./model-normalization"
export { resolveModelPipeline } from "./model-resolution-pipeline"
export type {
  ModelResolutionRequest,
  ModelResolutionProvenance,
  ModelResolutionResult,
} from "./model-resolution-types"
export { fuzzyMatchModel, isModelAvailable, getConnectedProviders, fetchAvailableModels, __resetModelCache, isModelCacheAvailable } from "./model-availability"
export { getBundledModelCapabilitiesSnapshot, getModelCapabilities, type GetModelCapabilitiesInput, type ModelCapabilities, type ModelCapabilitiesDiagnostics, type ModelCapabilitiesSnapshot, type ModelCapabilitiesSnapshotEntry } from "./model-capabilities"
export { MODELS_DEV_SOURCE_URL, buildModelCapabilitiesSnapshotFromModelsDev, fetchModelCapabilitiesSnapshot, createModelCapabilitiesCacheStore, readModelCapabilitiesCache, hasModelCapabilitiesCache, writeModelCapabilitiesCache, refreshModelCapabilitiesCache } from "./model-capabilities-cache"
export { initializeModelHeuristics, detectHeuristicModelFamily } from "./model-capability-heuristics"
export { resolveCompatibleModelSettings, type ModelSettingsCompatibilityInput, type ModelSettingsCompatibilityChange, type ModelSettingsCompatibilityResult } from "./model-settings-compatibility"
export { resolveFirstAvailableFallback, isAnyFallbackModelAvailable, isAnyProviderConnected } from "./fallback-model-availability"
export { createConnectedProvidersCacheStore, findProviderModelMetadata, readConnectedProvidersCache, hasConnectedProvidersCache, readProviderModelsCache, hasProviderModelsCache, writeProviderModelsCache, updateConnectedProvidersCache, _resetMemCacheForTesting, type ModelMetadata, type ProviderModelsCache } from "./connected-providers-cache"
export { resolveActualContextLimit, type ContextLimitModelCacheState } from "./context-limit-resolver"
export { isCallerOrchestrator } from "./session-utils"
export { isInsideTmux, getCurrentPaneId, isServerRunning, resetServerCheck, markServerRunningInProcess, getPaneDimensions, spawnTmuxPane, closeTmuxPane, replaceTmuxPane, spawnTmuxWindow, spawnTmuxSession, applyLayout, enforceMainPaneWidth, POLL_INTERVAL_BACKGROUND_MS, SESSION_TIMEOUT_MS, SESSION_MISSING_GRACE_MS, SESSION_READY_POLL_INTERVAL_MS, SESSION_READY_TIMEOUT_MS, type SpawnPaneResult, type SplitDirection, type PaneDimensions } from "./tmux"
export { parseModelSuggestion, promptWithModelSuggestionRetry, promptSyncWithModelSuggestionRetry, type ModelSuggestionInfo } from "./model-suggestion-retry"
export { getServerBasicAuthHeader, injectServerAuthIntoClient } from "./opencode-server-auth"
export { getServerBaseUrl, patchPart, deletePart } from "./opencode-http-api"
export { isPortAvailable, findAvailablePort, getAvailableServerPort, DEFAULT_SERVER_PORT, type AutoPortResult } from "./port-utils"
export { parseGitStatusPorcelainLine, parseGitStatusPorcelain, parseGitDiffNumstat, collectGitDiffStats, formatFileChanges, type GitFileStatus, type GitFileStat, type ParsedGitStatusPorcelainLine } from "./git-worktree"
export { safeCreateHook } from "./safe-create-hook"
export { truncateDescription } from "./truncate-description"
export { OPENCODE_STORAGE, MESSAGE_STORAGE, PART_STORAGE, SESSION_STORAGE } from "./opencode-storage-paths"
export { getMessageDir } from "./opencode-message-dir"
export { getOpenCodeCommandDirs, getOpenCodeSkillDirs } from "./opencode-command-dirs"
export { findProjectClaudeSkillDirs, findProjectAgentsSkillDirs, findProjectOpencodeSkillDirs, findProjectOpencodeCommandDirs } from "./project-discovery-dirs"
export { normalizeSDKResponse, type NormalizeSDKResponseOptions } from "./normalize-sdk-response"
export { isWindowsAppDataDirectory, resolveSessionDirectory } from "./session-directory-resolver"
export { normalizePromptTools, resolveInheritedPromptTools, type PromptToolPermission } from "./prompt-tools"
export { isCompactionAgent, hasCompactionPart, isCompactionMessage, getCompactionPartStorageDir, hasCompactionPartInStorage } from "./compaction-marker"
export { HIAI_INTERNAL_INITIATOR_MARKER, stripInternalInitiatorMarkers, createInternalAgentTextPart } from "./internal-initiator-marker"
export { discoverPluginCommandDefinitions, type PluginCommandDiscoveryOptions } from "./plugin-command-discovery"
export { SessionCategoryRegistry } from "./session-category-registry"
export { PLUGIN_NAME, LEGACY_PLUGIN_NAME, PUBLISHED_PACKAGE_NAME, ACCEPTED_PACKAGE_NAMES, CONFIG_BASENAME, LEGACY_CONFIG_BASENAME, LOG_FILENAME, CACHE_DIR_NAME } from "./plugin-identity"
export { logLegacyPluginStartupWarning } from "./log-legacy-plugin-startup-warning"
export { isTaskSystemEnabled, type TaskSystemConfig } from "./task-system-enabled"
export { parseToolsConfig } from "./parse-tools-config"
