import {
  cpSync,
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs"
import { join } from "node:path"

import type { BuiltinSkill } from "./types"
import { getOpenCodeConfigDir } from "../../shared/opencode-config-dir"

const GENERATED_MARKER = "<!-- Generated by hiai-opencode builtin skill materializer. -->"
const MANAGED_SKILL_METADATA = ".hiai-skill.json"
const LEGACY_MANAGED_DIR_MARKER = ".hiai-plugin-skill"

type ManagedSkillOrigin = "builtin" | "plugin"

interface ManagedSkillMetadata {
  name: string
  origin: ManagedSkillOrigin
  generatedBy: "hiai-opencode"
  assembledPath: string
  sourcePath: string
}

interface SkillRegistryEntry {
  name: string
  origin: ManagedSkillOrigin
  sourcePath: string
  assembledPath: string
}

function escapeYamlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
}

function buildSkillFrontmatter(skill: BuiltinSkill): string {
  const lines = [
    "---",
    `name: ${escapeYamlString(skill.name)}`,
    `description: ${escapeYamlString(skill.description)}`,
  ]

  if (skill.model) lines.push(`model: ${escapeYamlString(skill.model)}`)
  if (skill.agent) lines.push(`agent: ${escapeYamlString(skill.agent)}`)
  if (skill.argumentHint) {
    lines.push(`argument-hint: ${escapeYamlString(skill.argumentHint)}`)
  }
  if (skill.subtask) lines.push("subtask: true")

  lines.push("---", "", GENERATED_MARKER, "", skill.template.trim(), "")
  return lines.join("\n")
}

function shouldWriteSkillFile(skillFilePath: string): boolean {
  if (!existsSync(skillFilePath)) return true

  try {
    const existing = readFileSync(skillFilePath, "utf-8")
    return existing.includes(GENERATED_MARKER)
  } catch {
    return false
  }
}

function getSkillLayout() {
  const configDir = getOpenCodeConfigDir({ binary: "opencode" })
  const assembledSkillsDir = join(configDir, "skills")
  const sourceRootDir = join(configDir, ".hiai", "skills")
  const builtinSourceDir = join(sourceRootDir, "builtin")
  const pluginSourceDir = join(sourceRootDir, "plugin")

  mkdirSync(assembledSkillsDir, { recursive: true })
  mkdirSync(builtinSourceDir, { recursive: true })
  mkdirSync(pluginSourceDir, { recursive: true })

  return {
    configDir,
    assembledSkillsDir,
    sourceRootDir,
    builtinSourceDir,
    pluginSourceDir,
  }
}

function writeManagedSkillMetadata(
  targetDir: string,
  metadata: ManagedSkillMetadata,
): void {
  writeFileSync(
    join(targetDir, MANAGED_SKILL_METADATA),
    `${JSON.stringify(metadata, null, 2)}\n`,
    "utf-8",
  )
}

function readManagedSkillMetadata(targetDir: string): ManagedSkillMetadata | null {
  const metadataPath = join(targetDir, MANAGED_SKILL_METADATA)
  if (!existsSync(metadataPath)) {
    return null
  }

  try {
    return JSON.parse(readFileSync(metadataPath, "utf-8")) as ManagedSkillMetadata
  } catch {
    return null
  }
}

function isLegacyManagedSkillDir(targetDir: string, origin: ManagedSkillOrigin): boolean {
  if (origin === "plugin" && existsSync(join(targetDir, LEGACY_MANAGED_DIR_MARKER))) {
    return true
  }

  if (origin === "builtin") {
    const skillFilePath = join(targetDir, "SKILL.md")
    if (!existsSync(skillFilePath)) {
      return false
    }

    try {
      return readFileSync(skillFilePath, "utf-8").includes(GENERATED_MARKER)
    } catch {
      return false
    }
  }

  return false
}

function shouldSyncManagedSkillDir(targetDir: string, origin: ManagedSkillOrigin): boolean {
  if (!existsSync(targetDir)) return true

  const metadata = readManagedSkillMetadata(targetDir)
  if (metadata?.generatedBy === "hiai-opencode" && metadata.origin === origin) {
    return true
  }

  return isLegacyManagedSkillDir(targetDir, origin)
}

function shouldCleanupManagedSkillDir(targetDir: string, origin: ManagedSkillOrigin): boolean {
  const metadata = readManagedSkillMetadata(targetDir)
  if (metadata?.generatedBy === "hiai-opencode" && metadata.origin === origin) {
    return true
  }

  return isLegacyManagedSkillDir(targetDir, origin)
}

function cleanupRemovedManagedSkillDirs(
  rootDir: string,
  origin: ManagedSkillOrigin,
  expectedSkillNames: Set<string>,
): void {
  if (!existsSync(rootDir)) {
    return
  }

  for (const entry of readdirSync(rootDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    if (expectedSkillNames.has(entry.name)) continue

    const targetDir = join(rootDir, entry.name)
    if (shouldCleanupManagedSkillDir(targetDir, origin)) {
      rmSync(targetDir, { recursive: true, force: true })
    }
  }
}

function writeSkillRegistry(configDir: string, entries: SkillRegistryEntry[]): void {
  const registryDir = join(configDir, ".hiai")
  const assembledSkillsDir = join(configDir, "skills")

  mkdirSync(registryDir, { recursive: true })
  mkdirSync(assembledSkillsDir, { recursive: true })

  const sortedEntries = [...entries].sort((left, right) => left.name.localeCompare(right.name))
  const payload = {
    generatedBy: "hiai-opencode",
    generatedAt: new Date().toISOString(),
    summary: {
      total: sortedEntries.length,
      builtin: sortedEntries.filter((entry) => entry.origin === "builtin").length,
      plugin: sortedEntries.filter((entry) => entry.origin === "plugin").length,
    },
    layout: {
      assembledSkillsDir,
      builtinSourceDir: join(registryDir, "skills", "builtin"),
      pluginSourceDir: join(registryDir, "skills", "plugin"),
    },
    entries: sortedEntries,
  }

  writeFileSync(
    join(registryDir, "skill-registry.json"),
    `${JSON.stringify(payload, null, 2)}\n`,
    "utf-8",
  )

  const readme = [
    "# Hiai Skill Layout",
    "",
    "This directory tree is intentionally split into two layers:",
    "",
    "- `.opencode/.hiai/skills/plugin` contains mirrored plugin skill source directories.",
    "- `.opencode/.hiai/skills/builtin` contains generated built-in skill source directories.",
    "- `.opencode/skills` is the assembled working view that OpenCode indexes.",
    "",
    "See `.opencode/.hiai/skill-registry.json` for the exact origin of every assembled skill.",
    "",
  ].join("\n")

  writeFileSync(join(assembledSkillsDir, "README.md"), readme, "utf-8")
}

export function materializeBuiltinSkills(skills: BuiltinSkill[]): void {
  const { assembledSkillsDir, builtinSourceDir } = getSkillLayout()
  const expectedSkillNames = new Set(skills.map((skill) => skill.name))

  for (const skill of skills) {
    const sourceSkillDir = join(builtinSourceDir, skill.name)
    const sourceSkillFilePath = join(sourceSkillDir, "SKILL.md")
    const assembledSkillDir = join(assembledSkillsDir, skill.name)
    const assembledSkillFilePath = join(assembledSkillDir, "SKILL.md")
    const content = buildSkillFrontmatter(skill)

    mkdirSync(sourceSkillDir, { recursive: true })
    mkdirSync(assembledSkillDir, { recursive: true })

    if (!shouldWriteSkillFile(sourceSkillFilePath) || !shouldWriteSkillFile(assembledSkillFilePath)) {
      continue
    }

    writeFileSync(sourceSkillFilePath, content, "utf-8")
    writeFileSync(assembledSkillFilePath, content, "utf-8")

    writeManagedSkillMetadata(sourceSkillDir, {
      name: skill.name,
      origin: "builtin",
      generatedBy: "hiai-opencode",
      sourcePath: sourceSkillDir,
      assembledPath: assembledSkillDir,
    })
    writeManagedSkillMetadata(assembledSkillDir, {
      name: skill.name,
      origin: "builtin",
      generatedBy: "hiai-opencode",
      sourcePath: sourceSkillDir,
      assembledPath: assembledSkillDir,
    })
  }

  cleanupRemovedManagedSkillDirs(builtinSourceDir, "builtin", expectedSkillNames)
  cleanupRemovedManagedSkillDirs(assembledSkillsDir, "builtin", expectedSkillNames)
}

export function materializePluginSkillDirectories(pluginRootDir: string): void {
  const sourceSkillsDir = join(pluginRootDir, "skills")
  if (!existsSync(sourceSkillsDir)) {
    return
  }

  const { assembledSkillsDir, pluginSourceDir, configDir } = getSkillLayout()
  const registryEntries: SkillRegistryEntry[] = []
  const expectedSkillNames = new Set<string>()

  for (const entry of readdirSync(sourceSkillsDir, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue
    if (entry.name === "tmp") continue

    expectedSkillNames.add(entry.name)

    const sourceDir = join(sourceSkillsDir, entry.name)
    const mirroredSourceDir = join(pluginSourceDir, entry.name)
    const assembledDir = join(assembledSkillsDir, entry.name)

    if (
      !shouldSyncManagedSkillDir(mirroredSourceDir, "plugin") ||
      !shouldSyncManagedSkillDir(assembledDir, "plugin")
    ) {
      continue
    }

    rmSync(mirroredSourceDir, { recursive: true, force: true })
    rmSync(assembledDir, { recursive: true, force: true })

    cpSync(sourceDir, mirroredSourceDir, { recursive: true, force: true })
    cpSync(sourceDir, assembledDir, { recursive: true, force: true })

    writeManagedSkillMetadata(mirroredSourceDir, {
      name: entry.name,
      origin: "plugin",
      generatedBy: "hiai-opencode",
      sourcePath: sourceDir,
      assembledPath: assembledDir,
    })
    writeManagedSkillMetadata(assembledDir, {
      name: entry.name,
      origin: "plugin",
      generatedBy: "hiai-opencode",
      sourcePath: sourceDir,
      assembledPath: assembledDir,
    })

    registryEntries.push({
      name: entry.name,
      origin: "plugin",
      sourcePath: sourceDir,
      assembledPath: assembledDir,
    })
  }

  cleanupRemovedManagedSkillDirs(pluginSourceDir, "plugin", expectedSkillNames)
  cleanupRemovedManagedSkillDirs(assembledSkillsDir, "plugin", expectedSkillNames)

  for (const builtinEntry of readdirSync(assembledSkillsDir, { withFileTypes: true })) {
    if (!builtinEntry.isDirectory()) continue

    const assembledDir = join(assembledSkillsDir, builtinEntry.name)
    const metadata = readManagedSkillMetadata(assembledDir)
    if (metadata?.generatedBy !== "hiai-opencode" || metadata.origin !== "builtin") {
      continue
    }

    registryEntries.push({
      name: metadata.name,
      origin: "builtin",
      sourcePath: metadata.sourcePath,
      assembledPath: metadata.assembledPath,
    })
  }

  writeSkillRegistry(configDir, registryEntries)
}
